language:
  - ruby
  - node_js

node_js:
  - 0.10.7

before_install:
  - npm install grunt-cli bower -g
  - npm install
  - bower install
  - gem install compass

  # install Selenium
  - ./node_modules/protractor/bin/install_selenium_standalone

script:
  - DISPLAY=:99.0 grunt test:ci
