# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      # docker image with python and mkdocs on it already as well, based on gradle:4.6-alpine
      - image: yakworks/alpine-node:grails256
    #    branches:
    #      only:
    #        - master

    # working_directory: ~/repo

    environment:
      GRADLE_OPTS: "-Xmx1536m -Dorg.gradle.daemon=false" #daemon false doesn't seem to get picked up by fork
      TERM: dumb

    parallelism: 1
    # resource_class: large

    steps:
      - checkout
      # Download and cache dependencies

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "grails/ag-plugin/grails-app/conf/BuildConfig.groovy" }}

      # run compile twice, it fails the first time
      - run:
          name: grails compile
          command: |
            cd grails/ag-plugin
            grails compile || true
            grails compile

      - save_cache:
          paths: ["~/.m2", "~/.gradle", "~/.grails"]
          key: v1-dependencies-{{ checksum "grails/ag-plugin/grails-app/conf/BuildConfig.groovy" }}

      - run:
          name: ✔︎ npm install
          command: npm install

      - run:
          name: ✔︎ -- Checks js Tests [gradle check]
          command: grunt test

      # run tests!
      - run: |
          cd grails/ag-plugin
          grails test-app

      - run:
          name: Update js code
          command: ./script/update-ag-plugin

      - store_artifacts:
          path: plugin/build/reports/codenarc
          destination: codenarc/
      - store_artifacts:
          path: plugin/build/reports/tests/test/
          destination: unit/
      - store_artifacts:
          path: examples/test-app/build/reports/tests
          destination: test-app/
      - store_test_results:
          path: plugin/build/test-results
      - store_test_results:
          path: examples/test-app/build/test-results

      - run:
          name: grails publish-plugin
          command: >
            if [[ $CIRCLE_BRANCH == '1.x' ]]; then
              grails publish-plugin -repository=nine --non-interactive
            fi

orbs:
  compare-url: iynere/compare-url@1.1.0

workflows:
  version: 2.1
  build-flow:
    jobs:
      - build:
          context: 9cibot-context #context with shared ENV vars


