# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/alpine-node-gradle:1

    parallelism: 1
    # resource_class: large

    steps:
      - checkout
      - run: apk add yarn
      - run: yarn
      - run: yarn test

      - run:
          name: ✔︎ -- Checks Full Run Tests [gradle check]
          command: ./gradlew check --max-workers=2

      - run:
          name: Update js code
          command: ./script/update-ag-plugin

orbs:
  compare-url: iynere/compare-url@1.1.0

workflows:
  version: 2.1
  build-flow:
    jobs:
      - build:
          context: 9cibot-context #context with shared ENV vars

workflows:
  version: 2.1
  build-flow:
    jobs:
    - build:
        context: 9cibot-context # context with shared ENV vars
    # - build-grails:
    #     context: 9cibot-context
    #     requires: [build]
