---
restApi:
  invoice:
    entityClass: demo.Invoice
    includes:
     list: ['*', 'customer.*']
     get: ['*', 'customer.*']
     picklist: ['id', 'num', 'name']
     qSearch: ['num', 'name']

  customer:
    entityClass: demo.Customer

  tag:
    entityClass: demo.Tag

  tranState:
    entityClass: demo.TranState
    includes:
      picklist: ['id', 'name']
